Function Invoke-GenerateReadMe($RootDir) {
  $neo4jCommunityPkgs = @{}
  $neo4jCommunityDevPkgs = @{}

  # Categorise packages
  Get-ChildItem -Path "$RootDir" |
    ? { ($_.PSIsContainer) -and ($_.name -like 'neo4j-*') } | % {
      $dirName = $_.Name

      if ($dirName -like "neo4j-community-*") {
        $pkgVersion = $dirName.replace('neo4j-community-','')

        if ($pkgVersion -like '*-beta') {
          $pkgVersion = $pkgVersion.replace('-beta','')
          $neo4jCommunityDevPkgs.Add($pkgVersion,$_.Name)
        } else {
          $neo4jCommunityPkgs.Add($pkgVersion,$_.Name)
        }
      }
    }

  # Generate Readme texts
  $PkgListText = ""
  $neo4jCommunityPkgs.Keys | Sort-Object -Descending | % {
    $PkgListText += "* [Package version $($_)]($($neo4jCommunityPkgs[$_])/)`n"
  }
  $DevPkgListText = ""
  $neo4jCommunityDevPkgs.Keys | Sort-Object -Descending | % {
    $DevPkgListText += "* [Package version $($_)]($($neo4jCommunityDevPkgs[$_])/)`n"
  }

  $ReadmeContent = @"
## What is this?
This project is a collection Chocolatey packages to install Neo4j Community Edition and various plugins onto a Windows based computer.

## Neo4j Server

### neo4j-community
This package installs the Neo4j Server Community Edition

[Chocolatey Package](https://chocolatey.org/packages/neo4j-community)

Standard Releases
$PkgListText

Beta Releases
$DevPkgListText

## Libraries

### neo4j-lib-geoff
This package installs the GEOFF library

[Package version 0.5.0](neo4j-lib-geoff-0.5.0/)

[Chocolatey Package](https://chocolatey.org/packages/neo4j-lib-geoff)


### neo4j-lib-shelltools
This package installs the Shell Tools library

[Package version 2.0](neo4j-lib-shelltools-2.0/)

[Chocolatey Package](https://chocolatey.org/packages/neo4j-lib-shelltools)


### neo4j-lib-mapdb
This package installs the opencsv library

[Package version 0.9.3](neo4j-lib-mapdb-0.9.3/)

[Chocolatey Package](https://chocolatey.org/packages/neo4j-lib-mapdb)


### neo4j-lib-opencsv
This package installs the opencsv library

[Package version 2.3](neo4j-lib-opencsv-2.3/)

[Chocolatey Package](https://chocolatey.org/packages/neo4j-lib-opencsv)


### Links
https://chocolatey.org

http://neo4j.com/

---

This file is automatically generated
"@
  Write-Host "Creating README.md ..."
  Out-File -InputObject $ReadmeContent -FilePath "$($RootDir)\README.md" -Encoding ASCII -Force -Confirm:$false
}